# Token of the personal Discord account that will mirror messages.
# Learn how to find your account token here: https://www.androidauthority.com/get-discord-token-3149920/
token: "NTkwOTE2MjE5NTQ1MTkwNDg0.GH1cog.KzdW818DAZahw362wwf4Da62MAQmn87dhZuxYg"

# Status of the account that will mirror messages.
# Available options: online, offline, idle, dnd.
#
# Note that you should not be logged into the account
# when the bot starts for this option to take effect.
status: "online"

# Message sent in the console when a message is mirrored.
# You can set this to "" to disable it.
logMessage: "(%date%) Mirrored %author% message from %server%."

mirrors:
   1:
      channelIds:
         - "1163468396562743326"  # Source channel ID
      webhookUrls:
         - "https://discord.com/api/webhooks/1174835174903660574/NlklPZorVfrsa-YlUlqC12A5lBT-HlP2DLJjxEo3V2nl7tZKO_f1WJmkny2n88IGmrNB"  # Destination webhook URL
      # ... other options ...

   2:
      channelIds:
         - "1163467750560235520"  # Source channel ID
      webhookUrls:
         - "https://discord.com/api/webhooks/1174835171409797241/MLdhK7ayOiKvaeBdYNUGlxYe6scEtaTdvi7Wx1RrxVw9Gjn8hVqCtU7DvX8MamG1O_t9"  # Destination webhook URL
      # ... other options ...

   3:
      channelIds:
         - "1163467793824485406"  # Source channel ID
      webhookUrls:
         - "https://discord.com/api/webhooks/1174834950558732288/1lL1DhXfXL1snQH7v95t89obpI9ADlH1S1IfmTjbtMf6Qs5r8yFVcoIIHpi-N1FuIG09"  # Destination webhook URL
      # ... other options ...

   4:
      channelIds:
         - "1163467264729808916"  # Source channel ID
      webhookUrls:
         - "https://discord.com/api/webhooks/1174835163574845571/kXuu_3CHjC2hJS2eLPeDYNdj2ZNwtK3LlMn7iLNCGG3hymczC8r7uGy613vPA-WWrgF4"  # Destination webhook URL
      # ... other options ...

   5:
      channelIds:
         - "1163468485733646356"  # Source channel ID
      webhookUrls:
         - "https://discord.com/api/webhooks/1174835178221338784/k17UcJL52vI7kk6BZUYUTURwafS6X10cjzjPVz3rTWpd_FfyArJywjCS0sVzW5qAvGBb"  # Destination webhook URL
      # ... other options ...

   6:
      channelIds:
         - "1163472381847797791"  # Source channel ID
      webhookUrls:
         - "https://discord.com/api/webhooks/1174838540262199296/p2-ir_8Y3057ov6hAgL6mfbgDbiZsqqXYVRwUSgZLefhFrBmLa4DZMquwxagjkP-uh7R"  # Destination webhook URL
      # ... other options ...
